# Site settings
title: xOHami's Blog
description: xOHami's Blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: xOHami
user_description: IT Security, Data Science, Daily Life, Photo
user_title: Security Engineer
email: samdori9936@naver.com
twitter_username: samdori9936@naver.com
github_username:  yohankim
gplus_username:  samdori9936@gmail.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
